### ISSUE TITLE
error with CL Parser

### ISSUE THREAD

**Issue by mschwamb** [dirac-institute/sorcha#626]
sorcha -c ./demo/sorcha_config_demo.ini -p ./demo/sspp_testset_colours.txt -ob ./demo/sspp_testset_orbits.des  -pd ./demo/baseline_v2.0_1yr.db -o ./ -t testrun_e2e -f

Traceback (most recent call last):
  File "/Users/mschwamb/mambaforge/envs/sorcha/bin/sorcha", line 8, in <module>
    sys.exit(main())
  File "/Users/mschwamb/Research/python/lsst/survey_simulator/sorcha/src/sorcha/sorcha.py", line 452, in main
    cmd_args = PPCommandLineParser(args)
  File "/Users/mschwamb/Research/python/lsst/survey_simulator/sorcha/src/sorcha/modules/PPCommandLineParser.py", line 71, in PPCommandLineParser
    cmd_args_dict["oifoutput"] = args.er
AttributeError: 'Namespace' object has no attribute 'er'. Did you mean: 'ar'?

**Comment by mschwamb** [comment]
You might have already caught that is when it's defined. There's also another error at 
src/sorcha/modules/PPCommandLineParser.py  line 98

PPFindDirectoryOrExit(cmd_args_dict["ar_data_path"], -- > PPFindDirectoryOrExit(cmd_args_dict["ar_data_path"], "-ar")
