### ISSUE TITLE
update meta_kernel.txt  to accomodate long pathway names

### ISSUE THREAD

**Issue by mschwamb** [dirac-institute/sorcha#628]
sorcha -c ./demo/sorcha_config_demo.ini -p ./demo/sspp_testset_colours.txt -ob ./demo/sspp_testset_orbits.des  -pd ./demo/baseline_v2.0_1yr.db -o ./ -t testrun_e2e -f -ar ../ar_files
Traceback (most recent call last):

  File "/Users/mschwamb/mambaforge/envs/sorcha/bin/sorcha", line 8, in <module>
    sys.exit(main())
  File "/Users/mschwamb/Research/python/lsst/survey_simulator/sorcha/src/sorcha/sorcha.py", line 474, in main
    runLSSTSimulation(args, configs, pplogger)
  File "/Users/mschwamb/Research/python/lsst/survey_simulator/sorcha/src/sorcha/sorcha.py", line 168, in runLSSTSimulation
    observations = create_ephemeris(orbits_df, filterpointing, args, configs)
  File "/Users/mschwamb/Research/python/lsst/survey_simulator/sorcha/src/sorcha/ephemeris/simulation_driver.py", line 33, in create_ephemeris
    furnish_spiceypy(args)
  File "/Users/mschwamb/Research/python/lsst/survey_simulator/sorcha/src/sorcha/ephemeris/simulation_setup.py", line 66, in furnish_spiceypy
    spice.furnsh(meta_kernel)
  File "/Users/mschwamb/mambaforge/envs/sorcha/lib/python3.10/site-packages/spiceypy/spiceypy.py", line 139, in with_errcheck
    check_for_spice_error(f)
  File "/Users/mschwamb/mambaforge/envs/sorcha/lib/python3.10/site-packages/spiceypy/spiceypy.py", line 122, in check_for_spice_error
    raise dynamically_instantiate_spiceyerror(
spiceypy.utils.exceptions.SpiceNOSUCHFILE: 

Toolkit version: CSPICE_N0067

SPICE(NOSUCHFILE) --

The second file '/Users/mschwamb/Research/python/lsst/survey_simulator/ar_files/earth_720101_2306' specified by KERNELS_TO_LOAD in the file /Users/mschwamb/Research/python/lsst/survey_simulator/ar_files/meta_kernel.txt could not be located.

furnsh_c --> FURNSH --> ZZLDKER

If I don't used the -ar command, I get zero output from the ephemeris generator to the rest of the postprocessing steps

**Comment by mschwamb** [comment]
figured out this is being my directory path is too long 

\begindata

KERNELS_TO_LOAD=(
    '/Users/mschwamb/Research/python/lsst/survey_simulator/sorcha/sorcha/ar_files/naif0012.tls',
    '/Users/mschwamb/Research/python/lsst/survey_simulator/sorcha/sorcha/ar_files/earth_720101_230601.bpc',
    '/Users/mschwamb/Research/python/lsst/survey_simulator/sorcha/sorcha/ar_files/earth_200101_990825_predict.bpc',
    '/Users/mschwamb/Research/python/lsst/survey_simulator/sorcha/sorcha/ar_files/pck00010.pck',
    '/Users/mschwamb/Research/python/lsst/survey_simulator/sorcha/sorcha/ar_files/de440s.bsp',
    '/Users/mschwamb/Research/python/lsst/survey_simulator/sorcha/sorcha/ar_files/earth_latest_high_prec.bpc',
)

\begintext
meta_kernel.txt (END)

**Comment by matthewholman** [comment]
If you do something like what is below, does that resolve the problem?  Replace what is in PATH_VALUES with the common portion of your file paths.

\begindata
PATH_VALUES  = ( '/Users/mholman/Dropbox/support/kernels')

PATH_SYMBOLS = ( 'A' )

KERNELS_TO_LOAD=(
   '$A/naif0012.tls',
   '$A/earth_720101_070426.bpc',
   '$A/earth_200101_990628_predict.bpc',
   '$A/pck00010.tpc',
   '$A/de440s.bsp',
   '$A/earth_latest_high_prec.bpc')

\begintext

**Comment by mschwamb** [comment]
That worked. So we have a solution yay! Thanks @matthewholman  and @maxwest-uw for the debugging help
