### ISSUE TITLE
 ObjID already exists error

### ISSUE THREAD

**Issue by mschwamb** [dirac-institute/sorcha#974]
Traceback (most recent call last):
  File "/home/mschwamb/.conda/envs/sorcha/bin/sorcha", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mschwamb/sorcha/src/sorcha/sorcha.py", line 541, in main
    runLSSTSimulation(args, configs)
  File "/home/mschwamb/sorcha/src/sorcha/sorcha.py", line 343, in runLSSTSimulation
    PPWriteOutput(args, configs, observations, endChunk, verbose=args.verbose, lastchunk=lastChunk)
  File "/home/mschwamb/sorcha/src/sorcha/modules/PPOutput.py", line 227, in PPWriteOutput
    observations = PPOutWriteSqlite3(observations, out, lastchunk)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mschwamb/sorcha/src/sorcha/modules/PPOutput.py", line 100, in PPOutWriteSqlite3
    cur.execute("CREATE INDEX ObjID ON {} (ObjID)".format(tablename))
sqlite3.OperationalError: index ObjID already exists

**Comment by mschwamb** [comment]
This might because I had two processes running at the same time. I see two log files.  More posting so that we want to put this in the FAQ
